version: '3'

volumes:
  backend-sync-volume:
    external: true

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'

  backend:
    build:
      context: rails-nextjs-demo-backend
    volumes:
      - ./rails-nextjs-demo-backend:/usr/src/app
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_PORT: 3306
      DB_HOST: db
      RAILS_MAX_THREADS: 5
      RAILS_ENV: development

  frontend:
    build:
      context: rails-nextjs-demo-frontend
    volumes:
      - ./rails-nextjs-demo-frontend:/usr/src/app

  nginx:
    restart: always
    build:
      context: nginx
    environment:
      SERVER_HOST: localhost
      PORT: 80
    ports:
      - '80:80'
    links:
      - frontend:frontend
      - backend:backend
