source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.0'

gem 'rails', '~> 7.1.0'
gem 'mysql2', '~> 0.5.1'
gem 'puma', '~> 4.1'
gem 'bootsnap', '>= 1.4.3', require: false
gem 'rack-cors', '~> 2.0', '>= 2.0.2'
gem 'devise', '~> 4.9', '>= 4.9.4'
gem 'devise-jwt', '~> 0.12.1'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry-rails', '~> 0.3.6'
  gem 'pry-byebug', '~> 3.6'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]